config/routes.rb
Rails.application.routes.draw do
  get 'visitor/index'
  get 'subscriptions/upgrade'

  resources :plans do
    resources :subscriptions
    get 'switch_plans'
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "plans#index"
  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/plan.rb
class Plan < ApplicationRecord
  
  enum plan_type: {weekly: 0, monthly: 1, yearly:2}
  has_many :subscriptions, dependent: :destroy
   has_many :users
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :plan
  enum plan_status: {not_active: 0, active: 1};
    # before_create :update_user_id
  after_create_commit :active
  # def plan_active
  #   deactivate_plan_one
  #   # activate_plan_two
  # end

  # def deactivate_plan_one
  #   p "2222222222222222222222222222222222222222222"
  #  if current_user.subscription.plan_status == "active"
  #      p  current_user.plan.plan_type,"11111111111111111111111111111111111111111111111"
  #   # sub.plans.active.where(name: plan_one).first.try(:deactivate)
  #  end
  # end

  # def activate_plan_two
  #   sub.plan.where(name: plan_two).add if sub.have_plan_two? == false
  # end


  private
  def active 
    update_attribute :plan_status, "active"
  end
  # def update_user_id 
  #    p "innnnnnnnnnnnnnnnnnnnnnn"
    
  #     p "after ifffffffffffffffffffff"
  #     update_attribute :user_id, "nil"
    
  # end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :subscription
   has_one :plan, :through => :subscription
  
  enum role: {admin: 0, user: 1}
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:role])
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :authorize_admin

  # edit valid roles here      
  # VALID_ROLES = ['admin']
  
  # GET /plans or /plans.json
  def index
     @plans = Plan.all 
  end

  # GET /plans/1 or /plans/1.json
  def show
  end

  # GET /plans/new
  def new
    @plan = Plan.new
  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans or /plans.json
  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1 or /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to plan_url(@plan), notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1 or /plans/1.json
  def destroy
    @plan.destroy

    respond_to do |format|
      format.html { redirect_to plans_url, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
   def authorize_admin
      return unless !current_user.admin?
      redirect_to visitor_index_path , alert: 'Admins only!'
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def plan_params
      params.require(:plan).permit(:name, :price, :description, :plan_type)
    end
    
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    @plan = Plan.find(params[:plan_id])
          @sub = @plan.subscriptions.create(subscription_params) do |c|
            c.user_id = current_user.id
          end
          # redirect_to visitor_index_path , notice: "You have Subscribe The plan"
          if current_user.plan.plan_type == 'monthly'
            @sub = @plan.subscriptions.create(monthly_subscription_params) do |c|
            c.user_id = current_user.id
          end
        #  redirect_to '/subscriptions/yearly'
        redirect_to "/subscriptions/upgrade"
          end
           if current_user.plan.plan_type == 'weekly'
            @sub = @plan.subscriptions.create(weekly_subscription_params) do |c|
            c.user_id = current_user.id
          end
        #  redirect_to '/subscriptions/yearly'
        redirect_to "/subscriptions/upgrade"
          end
    
   end

  

  private
    def subscription_params
       @plan = Plan.find(params[:plan_id])
       if @plan.plan_type == 'weekly'
          @end_date = Date.today + 7
       elsif  @plan.plan_type == 'monthly'
          @end_date = Date.today + 1.month
        elsif  @plan.plan_type == 'yearly'
          @end_date = Date.today + 1.year
       end
      params.require(:subscription).permit(:start_date, :end_date, :plan_status).merge(start_date: Date.today , end_date: @end_date )
    end
    def monthly_subscription_params
      @plan = Plan.find(params[:plan_id])
          @end_date = Date.today + 1.year
      params.require(:subscription).permit(:start_date, :end_date, :plan_status).merge(start_date: Date.today , end_date: @end_date )
    end
   def weekly_subscription_params
     @plan = Plan.find(params[:plan_id])
          @end_date = Date.today + 1.month
      params.require(:subscription).permit(:start_date, :end_date, :plan_status).merge(start_date: Date.today , end_date: @end_date )
   end 
   
end

app/controllers/visitor_controller.rb
class VisitorController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @plans = Plan.all
    @sub = Subscription.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanSub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/shared/header"%>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
  <%= form.label :plan_type %>
  <%= form.select :plan_type, Plan.plan_types.keys %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>">
  <p>
    <strong>Name:</strong>
    <%= plan.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(plan.price) %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= plan.description %>
  </p>

  <p>
    <strong>Plan type:</strong>
    <%= plan.plan_type %>
  </p>

</div>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Show this plan", @plan %> |
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Plans</h1>

<div id="plans">
  <% @plans.each do |plan| %>
    <%= render plan %>
    <p>
      <%= link_to "Show this plan", plan %>
    </p>
  <% end %>
</div>
<%= link_to "New plan", new_plan_path %>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plan %>

<div>
  <%= link_to "Edit this plan", edit_plan_path(@plan) %> |
  <%= link_to "Back to plans", plans_path %>

  <%= button_to "Destroy this plan", @plan, method: :delete %>
</div>

app/views/shared/_header.html.erb
<% if user_signed_in? %>
<% if current_user.user? %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Subscribe</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <li><%= link_to 'Edit profile', edit_user_registration_path, class:"dropdown-item" %></li>
            <li> <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class:"dropdown-item" %>
            </li>
          <% else %>
            <li><%= link_to "Sign up", new_user_registration_path, class:"dropdown-item"  %></li>
            <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
          <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<% end %>
<% if current_user.admin? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Subscribe</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <%= link_to "Plans", plans_path, class:"nav-link active"%>
            <%# <a class="nav-link active" aria-current="page" href="#">Plans</a> %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              User
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path, class:"dropdown-item" %></li>
              <li> <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class:"dropdown-item" %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path, class:"dropdown-item"  %></li>
              <li><%= link_to "Login", new_user_session_path, class:"dropdown-item" %></li>
            <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>
<% end %>
<% end %>

app/views/subscriptions/_monthly.html.erb
This is monthly plan
<%= ((current_user.subscription.end_date)  - DateTime.now).to_i   %> Days remainning

<%= form_with model: [ current_user.plan, current_user.plan.subscriptions.build ] do |form| %>
    <p>
      <%= form.hidden_field :start_date %>
    </p>
    <p>
      <%= form.hidden_field :end_date %>
    </p>
    <div class="field">
    </div>
      <%= form.submit "Upgrade Plan" %>
  <% end %>

app/views/subscriptions/_weekly.html.erb
this is weekly plan
<%= ((current_user.subscription.end_date)  - DateTime.now).to_i   %>Days remainning 
  <%= form_with model: [ current_user.plan, current_user.plan.subscriptions.build ] do |form| %>
    <p>
      <%= form.hidden_field :start_date %>
    </p>
    <p>
      <%= form.hidden_field :end_date %>
    </p>
    <div class="field">
    </div>
      <%= form.submit "Upgrade Plan" %>
  <% end %>
   

app/views/subscriptions/_yearly.html.erb
This is yearly plan 
<%= ((current_user.subscription.end_date)  - DateTime.now).to_i   %>

app/views/subscriptions/upgrade.html.erb
<% if current_user.subscription.plan_id == 2 %>
  <%= ((current_user.subscription.end_date)  - DateTime.now).to_i   %>
<% end %>
<% if current_user.subscription.plan_id == 3 %>
  <%= ((current_user.subscription.end_date)  - DateTime.now).to_i   %>
<% end %>

app/views/visitor/index.html.erb
<% if  Subscription.exists?(:user_id => current_user) %>
<% if current_user.plan.plan_type == 'monthly' && current_user.subscription.end_date > Date.today %>
<%= render "/subscriptions/monthly"%>
 <%# ((created_at + 1.year) - DateTime.now).to_i / 1.day %>

<% elsif current_user.plan.plan_type == 'weekly'&& current_user.subscription.end_date > Date.today %>
<%= render "/subscriptions/weekly"%>

<% elsif current_user.plan.plan_type == 'yearly' && current_user.subscription.end_date > Date.today %>
<%= render "/subscriptions/yearly"%>
<% else %>
<p style="color: green"><%= notice %></p>
<h1>Plans</h1>
<div id="plans" >
  <% @plans.each do |plan| %>
   <div id="<%= dom_id plan %>"  >
    <div class="card mb-3" style="width: 18rem;">
      <div class="card-body">
        <p class="card-text"> 
          <p>
          <strong>Name:</strong>
          <%= plan.name %>
         
          </p>
          <p>
            <strong>Price:</strong>
            <%= number_to_currency(plan.price) %>
          </p>
          <p>
            <strong>Description:</strong>
            <%= plan.description %>
          </p>
          <p>
            <strong>Plan type:</strong>
            <%= plan.plan_type %>
          </p>
          <%= form_with model: [ plan, plan.subscriptions.build ] do |form| %>
          <p>
            <%= form.hidden_field :start_date %>
          </p>
          <p>
            <%= form.hidden_field :end_date %>
          </p>
          <div class="field">
          </div>
            <%= form.submit "Subscribe" %>
          <% end %>
        </p>
      </div>
    </div>
   </div>
  <% end %>
</div>
<% end %>
<% else %>
<p style="color: green"><%= notice %></p>
<h1>Plans</h1>
<div id="plans" >
  <% @plans.each do |plan| %>
   <div id="<%= dom_id plan %>"  >
    <div class="card mb-3" style="width: 18rem;">
      <div class="card-body">
        <p class="card-text"> 
          <p>
          <strong>Name:</strong>
          <%= plan.name %>
         
          </p>
          <p>
            <strong>Price:</strong>
            <%= number_to_currency(plan.price) %>
          </p>
          <p>
            <strong>Description:</strong>
            <%= plan.description %>
          </p>
          <p>
            <strong>Plan type:</strong>
            <%= plan.plan_type %>
          </p>
          <%= form_with model: [ plan, plan.subscriptions.build ] do |form| %>
          <p>
            <%= form.hidden_field :start_date %>
          </p>
          <p>
            <%= form.hidden_field :end_date %>
          </p>
          <div class="field">
          </div>
            <%= form.submit "Subscribe" %>
          <% end %>
        </p>
      </div>
    </div>
   </div>
  <% end %>
</div>
<% end %>